config/routes.rb
Rails.application.routes.draw do
  root to: "rooms#index"
  resources :rooms, only: [:index, :new, :create] do
    resources :records, only: [:index, :new]
    resources :comments, only: [:create, :update]
  end
  resources :records, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
end

app/models/hamada.rb
class Hamada < ApplicationRecord
  belongs_to :room
end

app/models/record.rb
class Record
  include ActiveModel::Model
  attr_accessor :s_point, :s_rank, :t_point, :t_rank, :h_point, :h_rank, :y_point, :y_rank, :turn, :room_id

  with_options presence: true do
    with_options format: {with: /\d/} do
      validates :s_point
      validates :t_point
      validates :h_point
      validates :y_point
    end
    validates :s_rank
    validates :t_rank
    validates :h_rank
    validates :y_rank
    validates :turn
    validates :room_id
  end

  def save
    Sueyoshi.create(s_point: s_point, s_rank: s_rank, turn: turn, room_id: room_id)
    Tamura.create(t_point: t_point, t_rank: t_rank, turn: turn, room_id: room_id)
    Hamada.create(h_point: h_point, h_rank: h_rank, turn: turn, room_id: room_id)
    Yamaguchi.create(y_point: y_point, y_rank: y_rank, turn: turn, room_id: room_id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :sueyoshis
  has_many :tamuras
  has_many :hamadas
  has_many :yamaguchis
  has_many :comments

  with_options presence: true do
    validates :number, format: {with: /\d{4,4}/}
    validates :date
  end
end

app/models/sueyoshi.rb
class Sueyoshi < ApplicationRecord
  belongs_to :room
end

app/models/tamura.rb
class Tamura < ApplicationRecord
  belongs_to :room
end

app/models/yamaguchi.rb
class Yamaguchi < ApplicationRecord
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["ITSUMEN_USER"] && password == ENV["ITSUMEN_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
    redirect_to root_path
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:s_comment, :t_comment, :h_comment, :y_comment).merge(room_id: params[:room_id])
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    @room = Room.find(params[:room_id])
    @sueyoshis = @room.sueyoshis.all
    
    @s_today_total = @sueyoshis.all.sum(:s_point)
    @t_today_total = @room.tamuras.all.sum(:t_point)
    @h_today_total = @room.hamadas.all.sum(:h_point)
    @y_today_total = @room.yamaguchis.all.sum(:y_point)
  end

  def new
    @room = Room.find(params[:room_id])
    @sueyoshis = @room.sueyoshis.all
    @sueyoshi = @room.sueyoshis.order(updated_at: :desc).limit(1)
    @record = Record.new
  end

  def create
    @room = Room.find(params[:room_id])
    @record = Record.new(record_params)
    if @record.valid?
      @record.save
      redirect_to room_records_path(room_id: @room.id)
    else
      redirect_to new_room_record_path(room_id: @room.id)
    end
  end

  private

  def record_params
    params.require(:record).permit(:s_point, :s_rank, :t_point, :t_rank, :h_point, :h_rank, :y_point, :y_rank,).merge(turn: params[:turn], room_id: params[:room_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all.order("created_at DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  private

  def room_params
    params.require(:room).permit(:number, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itsumen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class="title">〜いつメン麻雀広場〜</h1>
    </header>
    <div class="main-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/records/index.html.erb
<div class="page">
  <div class="r-index">
    <div class="page-title-text"><%= @room.date %>　<%= @room.number %>部屋</div>
    <div class="back-page"><%= link_to "最初に戻る", root_path, class:"back" %></div>
  </div>

  <div class="members">
    <div class="side-tag"></div>
    <div class="member"><%= link_to "末吉", "#", class:"person" %></div>
    <div class="member"><%= link_to "田村", "#", class:"person" %></div>
    <div class="member"><%= link_to "濱田", "#", class:"person" %></div>
    <div class="member"><%= link_to "山口", "#", class:"person" %></div>
  </div>

  <div class="r-records">
    <%# ↓ここを繰り返す %>
    <% unless @sueyoshis.empty? %>
      <% @sueyoshis.each do |sueyoshi| %>
        <div class="r-record">
          <div class="r-top-bar">
            <div class="side-tag"><%= sueyoshi.turn %>半荘目</div>
            <div class="member point num"><span class="<%= "red" if sueyoshi.s_point < 0 %>"><%= sueyoshi.s_point %></span></div>
            <div class="member point num"><span class="<%= "red" if Tamura.find(sueyoshi.id).t_point < 0 %>"><%= Tamura.find(sueyoshi.id).t_point %></span></div>
            <div class="member point num"><span class="<%= "red" if Hamada.find(sueyoshi.id).h_point < 0 %>"><%= Hamada.find(sueyoshi.id).h_point %></span></div>
            <div class="member point num"><span class="<%= "red" if Yamaguchi.find(sueyoshi.id).y_point < 0 %>"><%= Yamaguchi.find(sueyoshi.id).y_point %></span></div>
          </div>
        </div>
      <% end %>
    <% end %>
    <%# ↑ここまで繰り返す %>
  </div>

  <div class="r-results">
    <div class="result total">
      <div class="side-tag">合計</div>
      <div class="member num"><span class="<%= "red" if @s_today_total < 0 %>"><%= @s_today_total %></span></div>
      <div class="member num"><span class="<%= "red" if @t_today_total < 0 %>"><%= @t_today_total %></span></div>
      <div class="member num"><span class="<%= "red" if @h_today_total < 0 %>"><%= @h_today_total %></span></div>
      <div class="member num"><span class="<%= "red" if @y_today_total < 0 %>"><%= @y_today_total %></span></div>
    </div>
  </div>

  <div class="add">
    <div class="add-record">
      <%= link_to "半荘の結果を入力",  new_room_record_path, id:"add-battle", class:"add-battle" %>
    </div>
  </div>
</div>

app/views/records/new.html.erb
<div class="page">
  <div class="page-title">
    <% if @sueyoshis.empty? %>
      <div class="page-title-text">1半荘目の結果</div>
    <% else %>
      <% @sueyoshi.each do |sueyoshi| %>
        <div class="page-title-text"><%= sueyoshi.turn + 1 %>半荘目の結果</div>
      <% end %>
    <% end %>
    <div class="back-page"><%= link_to "#{@room.date}の対局に戻る", room_records_path(@room.id), class:"back" %></div>
  </div>

  <div class="members">
    <div class="side-tag"></div>
    <div class="member"><%= link_to "末吉", "#", class:"person" %></div>
    <div class="member"><%= link_to "田村", "#", class:"person" %></div>
    <div class="member"><%= link_to "濱田", "#", class:"person" %></div>
    <div class="member"><%= link_to "山口", "#", class:"person" %></div>
  </div>

  <%= form_with model: @record, ulr: records_path(room_id: @room.id), class:"record-form", id:"record-form", local: true do |f| %>
    <div class="record-boxes">
      <div class="top-bar">
        <div class="tag-title">点数</div>
        <div class="member point"><%= f.text_field :s_point, class:"point-box", id:"s-point", autofocus: true %></div>
        <div class="member point"><%= f.text_field :t_point, class:"point-box", id:"t-point" %></div>
        <div class="member point"><%= f.text_field :h_point, class:"point-box", id:"h-point" %></div>
        <div class="member point"><%= f.text_field :y_point, class:"point-box", id:"y-point" %></div>
      </div>
      <div class="under-bar">
        <div class="tag-title">順位</div>
        <div class="member point numb"><span class="rank" id="s-rank">1</span>位</div>
        <div class="member point numb"><span class="rank" id="t-rank">1</span>位</div>
        <div class="member point numb"><span class="rank" id="h-rank">1</span>位</div>
        <div class="member point numb"><span class="rank" id="y-rank">1</span>位</div>
      </div>
    </div>
    <div class="form record-submit">
      <div class="content"><%= f.submit "この半荘の結果を登録", class:"submit" %></div>
    </div>
    <%= f.text_field :s_rank, class:"rank-box", id:"s-rank-box" %>
    <%= f.text_field :t_rank, class:"rank-box", id:"t-rank-box" %>
    <%= f.text_field :h_rank, class:"rank-box", id:"h-rank-box" %>
    <%= f.text_field :y_rank, class:"rank-box", id:"y-rank-box" %>
    <% if @sueyoshis.empty? %>
      <input class="rank-box" name="turn" value="1">
    <% else %>
      <% @sueyoshi.each do |sueyoshi| %>
        <input class="rank-box" name="turn" value="<%= sueyoshi.turn + 1 %>">
      <% end %>
    <% end %>
    <input class="rank-box" name="room_id" value="<%= @room.id %>">
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="page">
  <div class="members">
    <div class="side-tag page-title"></div>
    <div class="member"><%= link_to "末吉", "#", class:"person" %></div>
    <div class="member"><%= link_to "田村", "#", class:"person" %></div>
    <div class="member"><%= link_to "濱田", "#", class:"person" %></div>
    <div class="member"><%= link_to "山口", "#", class:"person" %></div>
  </div>

  <div class="records">
    <%# ↓ここを繰り返す %>
    <% unless @rooms.empty? %>
      <% @rooms.each do |room| %>
        <% if Comment.find_by(room_id: room.id).nil? %>
          <%= form_with model: Comment.new, url: room_comments_path(room_id: room.id), class:"index-form", id:"index-form", local: true do |f| %>
            <div class="record">
              <div class="top-bar">
                <div class="side-tag link-bar">
                  <a href="/rooms/<%= room.id %>/records" class="to-records"><%= room.date %></a>
                </div>
                <div class="member point num"><span class="<%= "red" if room.sueyoshis.all.sum(:s_point) < 0 %>" ><%= room.sueyoshis.all.sum(:s_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.tamuras.all.sum(:t_point) < 0 %>" ><%= room.tamuras.all.sum(:t_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.hamadas.all.sum(:h_point) < 0 %>" ><%= room.hamadas.all.sum(:h_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.yamaguchis.all.sum(:y_point) < 0 %>" ><%= room.yamaguchis.all.sum(:y_point) %></span></div>
              </div>
              <div class="under-bar">
                <div class="side-tag"><%= f.submit "コメントを登録する", class:"comment-submit", id:"comment-submit" %></div>
                <div class="member point num"><%= f.text_field :s_comment, class:"text-field", id:"s-comment" %></div>
                <div class="member point num"><%= f.text_field :t_comment, class:"text-field", id:"t-comment" %></div>
                <div class="member point num"><%= f.text_field :h_comment, class:"text-field", id:"h-comment" %></div>
                <div class="member point num"><%= f.text_field :y_comment, class:"text-field", id:"y-comment" %></div>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= form_with model: Comment.find_by(room_id: room.id), url: room_comment_path(room_id: room.id, id: Comment.find_by(room_id: room.id).id), class:"index-form", id:"index-form", local: true do |f| %>
            <div class="record">
              <div class="top-bar">
                <div class="side-tag link-bar">
                  <a href="/rooms/<%= room.id %>/records" class="to-records"><%= room.date %></a>
                </div>
                <div class="member point num"><span class="<%= "red" if room.sueyoshis.all.sum(:s_point) < 0 %>" ><%= room.sueyoshis.all.sum(:s_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.tamuras.all.sum(:t_point) < 0 %>" ><%= room.tamuras.all.sum(:t_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.hamadas.all.sum(:h_point) < 0 %>" ><%= room.hamadas.all.sum(:h_point) %></span></div>
                <div class="member point num"><span class="<%= "red" if room.yamaguchis.all.sum(:y_point) < 0 %>" ><%= room.yamaguchis.all.sum(:y_point) %></span></div>
              </div>
              <div class="under-bar">
                <div class="side-tag"><%= f.submit "コメントを登録する", class:"comment-submit", id:"comment-submit" %></div>
                <div class="member point num"><%= f.text_field :s_comment, class:"text-field", id:"s-comment" %></div>
                <div class="member point num"><%= f.text_field :t_comment, class:"text-field", id:"t-comment" %></div>
                <div class="member point num"><%= f.text_field :h_comment, class:"text-field", id:"h-comment" %></div>
                <div class="member point num"><%= f.text_field :y_comment, class:"text-field", id:"y-comment" %></div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <%# ↑ここまで繰り返す %>
  </div>

  <div class="results">
    <div class="result total">
      <div class="side-tag">合計</div>
      <div class="member num"><span class="<%= "red" if Sueyoshi.all.sum(:s_point) < 0 %>" ><%= Sueyoshi.all.sum(:s_point) %></span></div>
      <div class="member num"><span class="<%= "red" if Tamura.all.sum(:t_point) < 0 %>" ><%= Tamura.all.sum(:t_point) %></span></div>
      <div class="member num"><span class="<%= "red" if Hamada.all.sum(:h_point) < 0 %>" ><%= Hamada.all.sum(:h_point) %></span></div>
      <div class="member num"><span class="<%= "red" if Yamaguchi.all.sum(:y_point) < 0 %>" ><%= Yamaguchi.all.sum(:y_point) %></span></div>
    </div>
    <div class="result">
      <div class="side-tag">平均順位</div>
      <div class="member num"><%= (Sueyoshi.all.sum(:s_rank)/Sueyoshi.select("id").count.to_f).round(2) %></div>
      <div class="member num"><%= (Tamura.all.sum(:t_rank)/Tamura.select("id").count.to_f).round(2) %></div>
      <div class="member num"><%= (Hamada.all.sum(:h_rank)/Hamada.select("id").count.to_f).round(2) %></div>
      <div class="member num"><%= (Yamaguchi.all.sum(:y_rank)/Yamaguchi.select("id").count.to_f).round(2) %></div>
    </div>
  </div>

  <div class="add">
    <div class="add-record">
      <%= link_to "対局を追加",  new_room_path, id:"add-battle", class:"add-battle" %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="page">
  <div class="page-title">
    <div class="page-title-text">対局作成</div>
    <div class="back-page"><%= link_to "戻る", root_path, class:"back" %></div>
  </div>

  <%= form_with model: @room, class:"form-with", local: true do |f| %>
    <div class="form">
      <div class="content"><%= f.label :date, "対局の日付", class:"label" %></div>
      <div class="content text"><%= f.date_field :date, class:"text-form" %></div>
    </div>
    <div class="form">
      <div class="content"><%= f.label :number, "部屋番号(半角数字)　L", class:"label" %></div>
      <div class="content text"><%= f.text_field :number, class:"text-form number" %></div>
    </div>
    <div class="form">
      <div class="content"><%= f.submit "新規対局を作成", class:"submit" %></div>
    </div>
  <% end %>
</div>